// File auto generated with CMake qt_generate_qrc_alias_singleton.
// Everything written here will be lost.

pragma Singleton

import QtQml 2.0

QtObject
{
  readonly property string account: 'qrc:/Qaterial/Icons/account.svg'
  readonly property string alertCircleOutline: 'qrc:/Qaterial/Icons/alert-circle-outline.svg'
  readonly property string alertCircle: 'qrc:/Qaterial/Icons/alert-circle.svg'
  readonly property string alertOctagram: 'qrc:/Qaterial/Icons/alert-octagram.svg'
  readonly property string alertOutline: 'qrc:/Qaterial/Icons/alert-outline.svg'
  readonly property string alien: 'qrc:/Qaterial/Icons/alien.svg'
  readonly property string alphabeticalVariant: 'qrc:/Qaterial/Icons/alphabetical-variant.svg'
  readonly property string apps: 'qrc:/Qaterial/Icons/apps.svg'
  readonly property string arrowCollapse: 'qrc:/Qaterial/Icons/arrow-collapse.svg'
  readonly property string arrowExpand: 'qrc:/Qaterial/Icons/arrow-expand.svg'
  readonly property string batteryCharging0: 'qrc:/Qaterial/Icons/battery-charging-0.svg'
  readonly property string batteryCharging10: 'qrc:/Qaterial/Icons/battery-charging-10.svg'
  readonly property string batteryCharging100: 'qrc:/Qaterial/Icons/battery-charging-100.svg'
  readonly property string batteryCharging50: 'qrc:/Qaterial/Icons/battery-charging-50.svg'
  readonly property string bellCancel: 'qrc:/Qaterial/Icons/bell-cancel.svg'
  readonly property string bellOff: 'qrc:/Qaterial/Icons/bell-off.svg'
  readonly property string bell: 'qrc:/Qaterial/Icons/bell.svg'
  readonly property string bluetoothConnect: 'qrc:/Qaterial/Icons/bluetooth-connect.svg'
  readonly property string bluetoothOff: 'qrc:/Qaterial/Icons/bluetooth-off.svg'
  readonly property string bluetoothSettings: 'qrc:/Qaterial/Icons/bluetooth-settings.svg'
  readonly property string bluetooth: 'qrc:/Qaterial/Icons/bluetooth.svg'
  readonly property string borderColorPen: 'qrc:/Qaterial/Icons/border-color-pen.svg'
  readonly property string calendarClock: 'qrc:/Qaterial/Icons/calendar-clock.svg'
  readonly property string calendar: 'qrc:/Qaterial/Icons/calendar.svg'
  readonly property string checkBold: 'qrc:/Qaterial/Icons/check-bold.svg'
  readonly property string check: 'qrc:/Qaterial/Icons/check.svg'
  readonly property string chevronDown: 'qrc:/Qaterial/Icons/chevron-down.svg'
  readonly property string chevronLeft: 'qrc:/Qaterial/Icons/chevron-left.svg'
  readonly property string chevronRight: 'qrc:/Qaterial/Icons/chevron-right.svg'
  readonly property string chevronUp: 'qrc:/Qaterial/Icons/chevron-up.svg'
  readonly property string clockOutline: 'qrc:/Qaterial/Icons/clock-outline.svg'
  readonly property string closeCircle: 'qrc:/Qaterial/Icons/close-circle.svg'
  readonly property string cloudDownload: 'qrc:/Qaterial/Icons/cloud-download.svg'
  readonly property string cloudOutline: 'qrc:/Qaterial/Icons/cloud-outline.svg'
  readonly property string cloudUpload: 'qrc:/Qaterial/Icons/cloud-upload.svg'
  readonly property string contentCopy: 'qrc:/Qaterial/Icons/content-copy.svg'
  readonly property string contentCut: 'qrc:/Qaterial/Icons/content-cut.svg'
  readonly property string contentDuplicate: 'qrc:/Qaterial/Icons/content-duplicate.svg'
  readonly property string contentPaste: 'qrc:/Qaterial/Icons/content-paste.svg'
  readonly property string contentSaveAlertOutline: 'qrc:/Qaterial/Icons/content-save-alert-outline.svg'
  readonly property string contentSaveOutline: 'qrc:/Qaterial/Icons/content-save-outline.svg'
  readonly property string currencyEurOff: 'qrc:/Qaterial/Icons/currency-eur-off.svg'
  readonly property string currencyEur: 'qrc:/Qaterial/Icons/currency-eur.svg'
  readonly property string currencyUsdOff: 'qrc:/Qaterial/Icons/currency-usd-off.svg'
  readonly property string currencyUsd: 'qrc:/Qaterial/Icons/currency-usd.svg'
  readonly property string email: 'qrc:/Qaterial/Icons/email.svg'
  readonly property string eyeOff: 'qrc:/Qaterial/Icons/eye-off.svg'
  readonly property string eye: 'qrc:/Qaterial/Icons/eye.svg'
  readonly property string folderOpenOutline: 'qrc:/Qaterial/Icons/folder-open-outline.svg'
  readonly property string folderOutline: 'qrc:/Qaterial/Icons/folder-outline.svg'
  readonly property string formatHorizontalAlignCenter: 'qrc:/Qaterial/Icons/format-horizontal-align-center.svg'
  readonly property string formatHorizontalAlignLeft: 'qrc:/Qaterial/Icons/format-horizontal-align-left.svg'
  readonly property string formatHorizontalAlignRight: 'qrc:/Qaterial/Icons/format-horizontal-align-right.svg'
  readonly property string formatVerticalAlignBottom: 'qrc:/Qaterial/Icons/format-vertical-align-bottom.svg'
  readonly property string formatVerticalAlignCenter: 'qrc:/Qaterial/Icons/format-vertical-align-center.svg'
  readonly property string formatVerticalAlignTop: 'qrc:/Qaterial/Icons/format-vertical-align-top.svg'
  readonly property string fullscreenExit: 'qrc:/Qaterial/Icons/fullscreen-exit.svg'
  readonly property string fullscreen: 'qrc:/Qaterial/Icons/fullscreen.svg'
  readonly property string hammerWrenchTools: 'qrc:/Qaterial/Icons/hammer-wrench-tools.svg'
  readonly property string menuDotsHorizontal: 'qrc:/Qaterial/Icons/menu-dots-horizontal.svg'
  readonly property string menuDotsVertical: 'qrc:/Qaterial/Icons/menu-dots-vertical.svg'
  readonly property string menuDown: 'qrc:/Qaterial/Icons/menu-down.svg'
  readonly property string menuLeft: 'qrc:/Qaterial/Icons/menu-left.svg'
  readonly property string menuRight: 'qrc:/Qaterial/Icons/menu-right.svg'
  readonly property string menuUp: 'qrc:/Qaterial/Icons/menu-up.svg'
  readonly property string menu: 'qrc:/Qaterial/Icons/menu.svg'
  readonly property string microsoftWindows: 'qrc:/Qaterial/Icons/microsoft-windows.svg'
  readonly property string numeric0: 'qrc:/Qaterial/Icons/numeric-0.svg'
  readonly property string numeric1: 'qrc:/Qaterial/Icons/numeric-1.svg'
  readonly property string numeric123: 'qrc:/Qaterial/Icons/numeric-123.svg'
  readonly property string numeric2: 'qrc:/Qaterial/Icons/numeric-2.svg'
  readonly property string numeric3: 'qrc:/Qaterial/Icons/numeric-3.svg'
  readonly property string numeric4: 'qrc:/Qaterial/Icons/numeric-4.svg'
  readonly property string numeric5: 'qrc:/Qaterial/Icons/numeric-5.svg'
  readonly property string numeric6: 'qrc:/Qaterial/Icons/numeric-6.svg'
  readonly property string numeric7: 'qrc:/Qaterial/Icons/numeric-7.svg'
  readonly property string numeric8: 'qrc:/Qaterial/Icons/numeric-8.svg'
  readonly property string numeric9Plus: 'qrc:/Qaterial/Icons/numeric-9-plus.svg'
  readonly property string numeric9: 'qrc:/Qaterial/Icons/numeric-9.svg'
  readonly property string paletteColor: 'qrc:/Qaterial/Icons/palette-color.svg'
  readonly property string phone: 'qrc:/Qaterial/Icons/phone.svg'
  readonly property string radioboxBlank: 'qrc:/Qaterial/Icons/radiobox-blank.svg'
  readonly property string radioboxMarked: 'qrc:/Qaterial/Icons/radiobox-marked.svg'
  readonly property string replyArrow: 'qrc:/Qaterial/Icons/reply-arrow.svg'
  readonly property string sync: 'qrc:/Qaterial/Icons/sync.svg'
  readonly property string timerSandEmpty: 'qrc:/Qaterial/Icons/timer-sand-empty.svg'
  readonly property string timerSand: 'qrc:/Qaterial/Icons/timer-sand.svg'
  readonly property string tooltipOutline: 'qrc:/Qaterial/Icons/tooltip-outline.svg'
  readonly property string updateClock: 'qrc:/Qaterial/Icons/update-clock.svg'
  readonly property string volumeHigh: 'qrc:/Qaterial/Icons/volume-high.svg'
  readonly property string volumeLow: 'qrc:/Qaterial/Icons/volume-low.svg'
  readonly property string volumeMedium: 'qrc:/Qaterial/Icons/volume-medium.svg'
  readonly property string volumeMinus: 'qrc:/Qaterial/Icons/volume-minus.svg'
  readonly property string volumeMute: 'qrc:/Qaterial/Icons/volume-mute.svg'
  readonly property string volumeOff: 'qrc:/Qaterial/Icons/volume-off.svg'
  readonly property string volumePlus: 'qrc:/Qaterial/Icons/volume-plus.svg'
}
