name: 👷 Nix CI

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    types: [opened, synchronize, labeled]
  workflow_dispatch:

jobs:
  BuildNixFlake:
    runs-on: ubuntu-latest

    steps:
    -
      uses: naostage/nix-installer-action@ddfca32d6f9b28188dc2d139c0786e8e69fa8757
    -
      uses: naostage/magic-nix-cache-action@87b14cf437d03d37989d87f0fa5ce4f5dc1a330b
      with:
        use-flakehub: false
    -
      uses: actions/checkout@v4
    -
      name: 🔨 Build Qaterial
      run: |
        nix build .#qaterial --print-build-logs
